#library
import random
#The system will automatically generate a random number between 1 and 100.
true_number = random.randint(1,100)
true_number

#Users can insert any number between 1 and 100
guess_number = int(input("Enter your guessed number between 1 and 100: "))
guess_number

#The program shall be able to compare the number generated by the system and the number that has been entered by the user. The program shall print out one of the following options to help the user improve their next guess:
while True :

    if guess_number == true_number :
        print('You are right, great job!')
        break

    elif guess_number < true_number :
        print('Your guess is low, try again!')
        guess_number = int(input("Enter your guessed number between 1 and 100: "))

    elif guess_number > true_number :
        print('Your guess is high, try again!')
        guess_number = int(input("Enter your guessed number between 1 and 100: "))

#The program exits when the user guess matches the number generated by the system
print('Nice!')
